export const GET_CART_DETAILS = 'GET_CART_DETAILS'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY'
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM'
