export const dummydata = [
  {
    _id: "639aab3096d129b1f7d740a9",
    id: 1004,
    brand: "glossier",
    name: "Stretch Concealer",
    price: "22.0",
    price_sign: "$",
    currency: "USD",
    image_link:
      "https://static-assets.glossier.com/production/spree/images/attachments/000/001/631/portrait_normal/SC_Carousel_1_copy_2.jpg?1506948615",
    product_link: "https://www.glossier.com/products/stretch-concealer",
    website_link: "https://www.glossier.com",
    description:
      "A traditional concealer sets to a stiff, flat, dry finish—a dead giveaway that you’re wearing it. Ours is a new type of concealer with elastic micro waxes that move with your face instead of caking on top of it, and nourishing oils that give a dewy, glowing finish. The buildable formula covers everything from dark circles to redness and blemishes. In five shades painstakingly developed to enhance, brighten, and—most importantly—completely disappear into the widest range of skin tones.",
    rating: null,
    category: "concealer",
    product_type: "foundation",
    tag_list: [],
    created_at: "2017-12-27T03:11:01.369Z",
    updated_at: "2017-12-27T03:12:42.235Z",
    product_api_url:
      "http://makeup-api.herokuapp.com/api/v1/products/1004.json",
    api_featured_image:
      "//s3.amazonaws.com/donovanbailey/products/api_featured_images/000/001/004/original/open-uri20171227-4-1wp63cr?1514344255",
    product_colors: [
      { hex_value: "#96644A", colour_name: "Deep" },
      { hex_value: "#4F3425", colour_name: "Rich" },
      { hex_value: "#BC8E5A", colour_name: "Dark" },
      { hex_value: "#E5BE93", colour_name: "Medium" },
      { hex_value: "#F1DBC3", colour_name: "Light" },
    ],
  },
  {
    _id: "639aab3096d129b1f7d74104",
    id: 912,
    brand: "nyx",
    name: "Gotcha Covered Concealer Pencil",
    price: "7.0",
    price_sign: "$",
    currency: "USD",
    image_link:
      "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw8ad0514f/ProductImages/2016/Face/Gotcha_Covered_Concealer_Pencil/gotchacoveredconcealerpencil_main.jpg?sw=390&sh=390&sm=fit",
    product_link:
      "https://www.nyxcosmetics.com/gotcha-covered-concealer-pencil/NYX_346.html?cgid=concealer",
    website_link: "https://www.nyxcosmetics.com",
    description:
      "Skin imperfections, beware! When it comes to covering up discoloration, our new Gotcha Covered Concealer Pencil does NOT mess around. Available in 20 blendable shades, this luxurious concealer is a master at spot concealing.",
    rating: null,
    category: "concealer",
    product_type: "foundation",
    tag_list: [],
    created_at: "2017-12-24T02:28:21.007Z",
    updated_at: "2017-12-24T02:30:17.143Z",
    product_api_url: "http://makeup-api.herokuapp.com/api/v1/products/912.json",
    api_featured_image:
      "//s3.amazonaws.com/donovanbailey/products/api_featured_images/000/000/912/original/open-uri20171224-4-abiui6?1514082616",
    product_colors: [
      { hex_value: "#F8DFC0", colour_name: "Alabaster" },
      { hex_value: "#F3D0B2", colour_name: "Light Ivory" },
      { hex_value: "#EFCBB1", colour_name: "Ivory" },
      { hex_value: "#EDC7A2", colour_name: "Light" },
      { hex_value: "#DDB997", colour_name: "Nude Beige" },
      { hex_value: "#DCBA97", colour_name: "Medium Olive" },
      { hex_value: "#DBB795", colour_name: "Honey Beige" },
      { hex_value: "#DDB174", colour_name: "Caramel Beige" },
      { hex_value: "#D7A568", colour_name: "Classic Tan" },
      { hex_value: "#D1A278", colour_name: "Golden" },
      { hex_value: "#CB9A6F", colour_name: "Sand" },
      { hex_value: "#B9884D", colour_name: "Deep Golden" },
      { hex_value: "#AA5E2A", colour_name: "Mahogany" },
      { hex_value: "#804F31", colour_name: "Cappuccino" },
      { hex_value: "#7B5236", colour_name: "Cocoa" },
      { hex_value: "#69442A", colour_name: "Deep Rich" },
      { hex_value: "#673C2B", colour_name: "Espresso" },
      { hex_value: "#653A29", colour_name: "Deep Espresso" },
      { hex_value: "#F4D1B3", colour_name: "Beige" },
    ],
  },
  {
    _id: "639aab3096d129b1f7d74105",
    id: 911,
    brand: "nyx",
    name: "Conceal, Correct, Contour Palette",
    price: "12.0",
    price_sign: "$",
    currency: "USD",
    image_link:
      "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dwbef45c94/ProductImages/Face/Conceal_Correct_Contour_Palette/800897831479_concealcorrectcontourpalette_light_main.jpg?sw=390&sh=390&sm=fit",
    product_link:
      "https://www.nyxcosmetics.com/conceal-correct-contour-palette/NYX_170.html?cgid=concealer",
    website_link: "https://www.nyxcosmetics.com",
    description:
      "Color-match your skin using our perfecting and correcting palettes to conceal, correct, or contour. With six shades to choose from in each set you can cover up problem spots even out imperfections and accentuate your best features in a flash. Use these buildable colors on their own or combine them to create the ideal tone.",
    rating: null,
    category: "concealer",
    product_type: "foundation",
    tag_list: [],
    created_at: "2017-12-24T02:28:19.928Z",
    updated_at: "2017-12-24T02:30:15.919Z",
    product_api_url: "http://makeup-api.herokuapp.com/api/v1/products/911.json",
    api_featured_image:
      "//s3.amazonaws.com/donovanbailey/products/api_featured_images/000/000/911/original/open-uri20171224-4-lx4vmq?1514082615",
    product_colors: [
      { hex_value: "#FFFEFC", colour_name: "Light" },
      { hex_value: "#FDF9F6", colour_name: "Medium" },
      { hex_value: "#F1F2F4", colour_name: "Deep" },
    ],
  },
  {
    _id: "639aab3096d129b1f7d74107",
    id: 909,
    brand: "nyx",
    name: "Dark Circle Concealer",
    price: "6.0",
    price_sign: "$",
    currency: "USD",
    image_link:
      "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw477d3d9a/ProductImages/Face/Dark_Circle_Concealer/800897822958_darkcircleconcealer_light_main.jpg?sw=390&sh=390&sm=fit",
    product_link:
      "https://www.nyxcosmetics.com/dark-circle-concealer/NYX_133.html?cgid=concealer",
    website_link: "https://www.nyxcosmetics.com",
    description:
      "A serious solution for one of beauty’s most challenging problems! No fancy names just a product that can be counted on to do the job. The product glides on without looking thick or obvious. The subtle hint of orange counteracts the appearance of dark circles while natural skin-toned pigments work in unison to provide the ultimate coverage.",
    rating: null,
    category: "concealer",
    product_type: "foundation",
    tag_list: [],
    created_at: "2017-12-24T02:28:17.702Z",
    updated_at: "2017-12-24T02:30:13.878Z",
    product_api_url: "http://makeup-api.herokuapp.com/api/v1/products/909.json",
    api_featured_image:
      "//s3.amazonaws.com/donovanbailey/products/api_featured_images/000/000/909/original/open-uri20171224-4-vt9rh6?1514082613",
    product_colors: [
      { hex_value: "#ECAA87", colour_name: "Fair" },
      { hex_value: "#EA9B70", colour_name: "Light" },
      { hex_value: "#E5895A", colour_name: "Medium" },
      { hex_value: "#A96540", colour_name: "Deep" },
    ],
  },
  {
    _id: "639aab3096d129b1f7d74108",
    id: 908,
    brand: "nyx",
    name: "Gotcha Covered Concealer",
    price: "6.0",
    price_sign: "$",
    currency: "USD",
    image_link:
      "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw947da0d5/ProductImages/Face/Gotcha_Covered_Concealer/gotchacoveredconcealer_main.jpg?sw=390&sh=390&sm=fit",
    product_link:
      "https://www.nyxcosmetics.com/gotcha-covered-concealer/NYX_203.html?cgid=concealer",
    website_link: "https://www.nyxcosmetics.com",
    description:
      "Gotcha Covered Concealer always has your back! Now available in 10 more gorgeous shades, our waterproof, full coverage concealer effectively covers up discolorations and imperfections without creasing or caking. Infused with coconut oil, this highly blendable concealer also leaves your face with a healthy-looking glow.",
    rating: null,
    category: "concealer",
    product_type: "foundation",
    tag_list: [],
    created_at: "2017-12-24T02:28:15.481Z",
    updated_at: "2017-12-24T02:30:12.047Z",
    product_api_url: "http://makeup-api.herokuapp.com/api/v1/products/908.json",
    api_featured_image:
      "//s3.amazonaws.com/donovanbailey/products/api_featured_images/000/000/908/original/open-uri20171224-4-1980tbf?1514082611",
    product_colors: [
      { hex_value: "#E9CFB6", colour_name: "Alabaster" },
      { hex_value: "#E7C7AE", colour_name: "Ivory" },
      { hex_value: "#E0C2AA", colour_name: "Soft Ivory" },
      { hex_value: "#D6B79B", colour_name: "Light" },
      { hex_value: "#E0C1A5", colour_name: "Natural" },
      { hex_value: "#DCB18F", colour_name: "Beige" },
      { hex_value: "#D1A77D", colour_name: "Medium" },
      { hex_value: "#CFA984", colour_name: "Medium Olive" },
      { hex_value: "#D5AB81", colour_name: "Fresh Beige" },
      { hex_value: "#C9A37E", colour_name: "Golden" },
      { hex_value: "#B99774", colour_name: "Tan" },
      { hex_value: "#BB906D", colour_name: "Sand" },
      { hex_value: "#B08767", colour_name: "Deep Honey" },
      { hex_value: "#957151", colour_name: "Deep" },
      { hex_value: "#A47C59", colour_name: "Cappuccino" },
      { hex_value: "#997551", colour_name: "Deep Caramel" },
      { hex_value: "#937052", colour_name: "Mocha" },
      { hex_value: "#715138", colour_name: "Ebony" },
      { hex_value: "#72573C", colour_name: "Cocoa" },
      { hex_value: "#5E4433", colour_name: "Espresso" },
    ],
  },
  {
    _id: "639aab3096d129b1f7d74109",
    id: 907,
    brand: "nyx",
    name: "Color Correcting Palette",
    price: "12.0",
    price_sign: "$",
    currency: "USD",
    image_link:
      "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dwb6d96368/ProductImages/Face/Color_Correcting_Palette/800897834722_colorcorrectingpalette_main.jpg?sw=390&sh=390&sm=fit",
    product_link:
      "https://www.nyxcosmetics.com/color-correcting-palette/NYX_171.html?cgid=concealer",
    website_link: "https://www.nyxcosmetics.com",
    description:
      "Treat your face to the ultimate concealer palette in six color correcting shades. Customizable to create your ideal shade to cover imperfections the lightweight formula glides on for an ultra-smooth finish and leaves skin feeling soft and supple.",
    rating: null,
    category: "concealer",
    product_type: "foundation",
    tag_list: [],
    created_at: "2017-12-24T02:28:14.774Z",
    updated_at: "2017-12-24T02:30:11.232Z",
    product_api_url: "http://makeup-api.herokuapp.com/api/v1/products/907.json",
    api_featured_image:
      "//s3.amazonaws.com/donovanbailey/products/api_featured_images/000/000/907/original/open-uri20171224-4-1b7ug0q?1514082611",
    product_colors: [],
  },
  {
    _id: "639aab3096d129b1f7d7410a",
    id: 906,
    brand: "nyx",
    name: "Concealer Jar",
    price: "5.0",
    price_sign: "$",
    currency: "USD",
    image_link:
      "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw04c31800/ProductImages/Face/Concealer_Jar/concealerjar_main.jpg?sw=390&sh=390&sm=fit",
    product_link:
      "https://www.nyxcosmetics.com/concealer-jar/NYX_011.html?cgid=concealer",
    website_link: "https://www.nyxcosmetics.com",
    description:
      "Obscure imperfections and blur away problem areas with one of our Concealer Jars. Now available in 10 more shades to accommodate an even wider range of skin tones, this creamy formula stands up to the villains of unwelcome imperfections with a vengeance.",
    rating: null,
    category: "concealer",
    product_type: "foundation",
    tag_list: [],
    created_at: "2017-12-24T02:28:11.932Z",
    updated_at: "2017-12-24T02:30:08.254Z",
    product_api_url: "http://makeup-api.herokuapp.com/api/v1/products/906.json",
    api_featured_image:
      "//s3.amazonaws.com/donovanbailey/products/api_featured_images/000/000/906/original/open-uri20171224-4-gko26q?1514082608",
    product_colors: [
      { hex_value: "#FCDAB5", colour_name: "Alabaster" },
      { hex_value: "#FCCAA5", colour_name: "Porcelain" },
      { hex_value: "#FCCEAD", colour_name: "Fair" },
      { hex_value: "#EFB590", colour_name: "Light" },
      { hex_value: "#DAA677", colour_name: "Nude Beige" },
      { hex_value: "#D9A073", colour_name: "Beige" },
      { hex_value: "#CDA170", colour_name: "Sand Beige" },
      { hex_value: "#CB885E", colour_name: "Medium" },
      { hex_value: "#DB9A74", colour_name: "Glow" },
      { hex_value: "#CC9D69", colour_name: "Fresh Beige" },
      { hex_value: "#D0925F", colour_name: "Golden" },
      { hex_value: "#BC8B50", colour_name: "Caramel" },
      { hex_value: "#BB7B4B", colour_name: "Tan" },
      { hex_value: "#B9743D", colour_name: "Deep Golden" },
      { hex_value: "#A76938", colour_name: "Nutmeg" },
      { hex_value: "#B1703A", colour_name: "Cappuccino" },
      { hex_value: "#A76C40", colour_name: "Cocoa" },
      { hex_value: "#885333", colour_name: "Deep Rich" },
      { hex_value: "#805332", colour_name: "Espresso" },
      { hex_value: "#71482C", colour_name: "Deep Espresso" },
      { hex_value: "#F8D383", colour_name: "Yellow" },
      { hex_value: "#D5BCE6", colour_name: "Lavender" },
      { hex_value: "#BDE0C0", colour_name: "Green" },
      { hex_value: "#FB772F", colour_name: "Orange" },
    ],
  },
  {
    _id: "639aab3096d129b1f7d7410b",
    id: 905,
    brand: "nyx",
    name: "HD Photogenic Concealer Wand",
    price: "5.0",
    price_sign: "$",
    currency: "USD",
    image_link:
      "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw10ab1d12/ProductImages/2016/Face/HD_Photogenic_Concealer_Wand/concealerwand_main.jpg?sw=390&sh=390&sm=fit",
    product_link:
      "https://www.nyxcosmetics.com/hd-photogenic-concealer-wand/NYX_013.html?cgid=concealer",
    website_link: "https://www.nyxcosmetics.com",
    description:
      "Now available in 12 more shades to accommodate an even wider range of skin tones, our best-selling HD Studio Photogenic Concealer effectively covers imperfections, discoloration and under-eye circles without ever looking cakey or obvious. The result is beautiful, natural-looking coverage you can count on.",
    rating: null,
    category: "concealer",
    product_type: "foundation",
    tag_list: [],
    created_at: "2017-12-24T02:28:08.470Z",
    updated_at: "2017-12-24T02:30:04.357Z",
    product_api_url: "http://makeup-api.herokuapp.com/api/v1/products/905.json",
    api_featured_image:
      "//s3.amazonaws.com/donovanbailey/products/api_featured_images/000/000/905/original/open-uri20171224-4-1tmsfyh?1514082604",
    product_colors: [
      { hex_value: "#EBC7A3", colour_name: "Alabaster" },
      { hex_value: "#ECC3A5", colour_name: "Porcelain" },
      { hex_value: "#EABF9D", colour_name: "Fair" },
      { hex_value: "#E6B897", colour_name: "Light" },
      { hex_value: "#DEB391", colour_name: "Nude Beige" },
      { hex_value: "#DAB08A", colour_name: "Beige" },
      { hex_value: "#D2A67F", colour_name: "Sand Beige" },
      { hex_value: "#D5A080", colour_name: "Medium" },
      { hex_value: "#D49F7D", colour_name: "Glow" },
      { hex_value: "#CD9E74", colour_name: "Fresh Beige" },
      { hex_value: "#CE9872", colour_name: "Golden" },
      { hex_value: "#C5966A", colour_name: "Caramel" },
      { hex_value: "#BE895F", colour_name: "Tan" },
      { hex_value: "#BB8255", colour_name: "Deep Golden" },
      { hex_value: "#B2794C", colour_name: "Nutmeg" },
      { hex_value: "#945D3F", colour_name: "Cappuccino" },
      { hex_value: "#93633F", colour_name: "Cocoa" },
      { hex_value: "#83573E", colour_name: "Deep Rich" },
      { hex_value: "#7C4F38", colour_name: "Espresso" },
      { hex_value: "#6B3E27", colour_name: "Deep Espresso" },
      { hex_value: "#F2CC8E", colour_name: "Yellow" },
      { hex_value: "#BFB3C9", colour_name: "Lavender" },
      { hex_value: "#A0C8AD", colour_name: "Green" },
    ],
  },
  {
    _id: "639aab3096d129b1f7d74145",
    id: 847,
    brand: "fenty",
    name: "MATCH STIX - Matte Skinstick",
    price: "25.0",
    price_sign: "$",
    currency: "USD",
    image_link:
      "https://www.fentybeauty.com/dw/image/v2/AAXW_PRD/on/demandware.static/-/Sites-itemmaster_FENTY/default/dw50617083/hi-res/FB30003_FB3009.jpg?sw=550 550w",
    product_link:
      "https://www.fentybeauty.com/match-stix/matte-skinstick/FB30003.html?dwvar_FB30003_color=FB3009",
    website_link: "https://www.fentybeauty.com",
    description:
      "A magnetized makeup stick in a longwear, light-as-air matte formula to conceal, correct, contour, and touch up in 20 shades.",
    rating: null,
    category: "concealer",
    product_type: "foundation",
    tag_list: [],
    created_at: "2017-12-23T23:43:36.178Z",
    updated_at: "2017-12-25T23:51:22.527Z",
    product_api_url: "http://makeup-api.herokuapp.com/api/v1/products/847.json",
    api_featured_image:
      "//s3.amazonaws.com/donovanbailey/products/api_featured_images/000/000/847/original/open-uri20171224-4-1se9mcb?1514074989",
    product_colors: [
      { hex_value: "#C9A074", colour_name: "Maple - Neutral" },
      { hex_value: "#683525", colour_name: "Espresso - Cool" },
      { hex_value: "#D9A877", colour_name: "Maple - Neutral" },
      { hex_value: "#EABC95", colour_name: "Bamboo - Neutral" },
      { hex_value: "#EAB087", colour_name: "Honey - Warm Peach" },
      { hex_value: "#C59072", colour_name: "Mocha - Cool" },
      { hex_value: "#C5885D", colour_name: "Suede - Warm" },
      { hex_value: "#CE8E5C", colour_name: "Latte - Warm" },
      { hex_value: "#E1AA7F", colour_name: "Caramel - Cool" },
      { hex_value: "#DA9F65", colour_name: "Wheat - Warm" },
      { hex_value: "#EFAE83", colour_name: "Peach - Cool Peach" },
      { hex_value: "#F6D5B6", colour_name: "Linen - Cool" },
      { hex_value: "#7C411F", colour_name: "Truffle - Neutral" },
      { hex_value: "#B08B72", colour_name: "Amber - Cool Contour" },
      { hex_value: "#CF936A", colour_name: "Cocoa - Cool" },
      { hex_value: "#CB9064", colour_name: "Walnut - Neutral" },
      { hex_value: "#DA9D6F", colour_name: "Almond - Cool" },
      { hex_value: "#E2AE83", colour_name: "Sand - Neutral" },
      { hex_value: "#F7D2AC", colour_name: "French Vanilla - Warm" },
      { hex_value: "#F5DABE", colour_name: "Porcelain - Cool" },
    ],
  },
  {
    _id: "639aab3096d129b1f7d7415a",
    id: 826,
    brand: "clinique",
    name: "Acne Solutions&trade; Clearing Concealer",
    price: "18.0",
    price_sign: "$",
    currency: "USD",
    image_link:
      "https://www.clinique.com/media/export/cms/products/181x209/clq_6N4T_181x209.png",
    product_link:
      "https://www.clinique.com/product/1596/6045/makeup/concealers/acne-solutions-clearing-concealer",
    website_link: "https://www.clinique.com",
    description:
      "Medicated concealer helps clear and prevent blemishes. Gentle, soothing formula provides natural-looking coverage as blemishes heal. In three skin tone shades to wear alone, under makeup or for touch-ups. Plus, a green tint to visually correct redness. Oil free.",
    rating: null,
    category: "concealer",
    product_type: "foundation",
    tag_list: [],
    created_at: "2017-12-23T23:43:01.437Z",
    updated_at: "2017-12-23T23:43:07.382Z",
    product_api_url: "http://makeup-api.herokuapp.com/api/v1/products/826.json",
    api_featured_image:
      "//s3.amazonaws.com/donovanbailey/products/api_featured_images/000/000/826/original/data?1514072587",
    product_colors: [
      { hex_value: "#EFD1B3", colour_name: "Shade 01" },
      { hex_value: "#D5AA86", colour_name: "Shade 03" },
      { hex_value: "#F0C9A0", colour_name: "Shade 02" },
    ],
  },
  {
    _id: "639aab3096d129b1f7d7415b",
    id: 825,
    brand: "clinique",
    name: "Line Smoothing Concealer",
    price: "20.0",
    price_sign: "$",
    currency: "USD",
    image_link:
      "https://www.clinique.com/media/export/cms/products/181x209/clq_65EF_181x209.png",
    product_link:
      "https://www.clinique.com/product/1596/6088/makeup/concealers/line-smoothing-concealer",
    website_link: "https://www.clinique.com",
    description:
      'Oil-free formula actually "bridges" fine lines and wrinkles, smoothing and minimizing them for an instantly firmer look. Skin-brightening ingredients help counteract shadows, reduce redness, give skin more even tone. Ophthalmologist tested. Long-lasting, buildable.',
    rating: null,
    category: "concealer",
    product_type: "foundation",
    tag_list: [],
    created_at: "2017-12-23T23:43:00.823Z",
    updated_at: "2017-12-23T23:43:05.599Z",
    product_api_url: "http://makeup-api.herokuapp.com/api/v1/products/825.json",
    api_featured_image:
      "//s3.amazonaws.com/donovanbailey/products/api_featured_images/000/000/825/original/data?1514072585",
    product_colors: [
      { hex_value: "#D19C83", colour_name: "Light" },
      { hex_value: "#C49381", colour_name: "Moderately Fair" },
      { hex_value: "#AD7D68", colour_name: "Medium" },
      { hex_value: "#BB9171", colour_name: "Medium Beige" },
      { hex_value: "#C9916C", colour_name: "Medium Honey" },
      { hex_value: "#916148", colour_name: "Deep" },
    ],
  },
  {
    _id: "639aab3096d129b1f7d7415c",
    id: 824,
    brand: "clinique",
    name: "All About Eyes&trade; Concealer",
    price: "20.0",
    price_sign: "$",
    currency: "USD",
    image_link:
      "https://www.clinique.com/media/export/cms/products/181x209/clq_6FKW_181x209.png",
    product_link:
      "https://www.clinique.com/product/1596/5161/makeup/concealers/all-about-eyes-concealer",
    website_link: "https://www.clinique.com",
    description: "",
    rating: null,
    category: "concealer",
    product_type: "foundation",
    tag_list: [],
    created_at: "2017-12-23T23:43:00.157Z",
    updated_at: "2017-12-23T23:43:04.907Z",
    product_api_url: "http://makeup-api.herokuapp.com/api/v1/products/824.json",
    api_featured_image:
      "//s3.amazonaws.com/donovanbailey/products/api_featured_images/000/000/824/original/data?1514072584",
    product_colors: [
      { hex_value: "#F1CFB2", colour_name: "Light Neutral" },
      { hex_value: "#E7BFA1", colour_name: "Light Petal" },
      { hex_value: "#E2B18C", colour_name: "Medium Petal" },
      { hex_value: "#DAA16D", colour_name: "Medium Beige" },
      { hex_value: "#D49167", colour_name: "Medium Honey" },
      { hex_value: "#A77A55", colour_name: "Deep Golden" },
    ],
  },
  {
    _id: "639aab3096d129b1f7d7415d",
    id: 823,
    brand: "clinique",
    name: "Advanced Concealer",
    price: "20.0",
    price_sign: "$",
    currency: "USD",
    image_link:
      "https://www.clinique.com/media/export/cms/products/181x209/clq_6296_181x209.png",
    product_link:
      "https://www.clinique.com/product/1596/6278/makeup/concealers/advanced-concealer",
    website_link: "https://www.clinique.com",
    description:
      "Cream-to-powder concealer delivers long-lasting, intensive camouflage. With daily use, helps firm and smooth. Won't creep or fade. Ophthalmologist tested.",
    rating: null,
    category: "concealer",
    product_type: "foundation",
    tag_list: [],
    created_at: "2017-12-23T23:42:59.720Z",
    updated_at: "2017-12-23T23:43:04.510Z",
    product_api_url: "http://makeup-api.herokuapp.com/api/v1/products/823.json",
    api_featured_image:
      "//s3.amazonaws.com/donovanbailey/products/api_featured_images/000/000/823/original/data?1514072584",
    product_colors: [{ hex_value: "#CC9D82", colour_name: "Matte Light" }],
  },
  {
    _id: "639aab3096d129b1f7d7415e",
    id: 822,
    brand: "clinique",
    name: "Airbrush Concealer&trade;",
    price: "22.0",
    price_sign: "$",
    currency: "USD",
    image_link:
      "https://www.clinique.com/media/export/cms/products/181x209/clq_6CM2_181x209.png",
    product_link:
      "https://www.clinique.com/product/1596/5011/makeup/concealers/airbrush-concealer",
    website_link: "https://www.clinique.com",
    description:
      "Instantly helps soften the look of fine lines and wrinkles. Light-diffusing optics brighten shadows. Creamy, light formula flows through for smooth brush-on, precision application. Ophthalmologist tested.",
    rating: null,
    category: "concealer",
    product_type: "foundation",
    tag_list: [],
    created_at: "2017-12-23T23:42:59.147Z",
    updated_at: "2017-12-23T23:43:03.833Z",
    product_api_url: "http://makeup-api.herokuapp.com/api/v1/products/822.json",
    api_featured_image:
      "//s3.amazonaws.com/donovanbailey/products/api_featured_images/000/000/822/original/data?1514072583",
    product_colors: [
      { hex_value: "#FFBEB0", colour_name: "Fair" },
      { hex_value: "#F7B9AC", colour_name: "NEW Illuminator" },
      { hex_value: "#F7CDA1", colour_name: "NEW Fair Cream" },
      { hex_value: "#E8BE92", colour_name: "NEW Neutral Cream" },
      { hex_value: "#E7B295", colour_name: "NEW Light Honey" },
      { hex_value: "#DCAC8A", colour_name: "Neutral Fair" },
      { hex_value: "#DCB08C", colour_name: "NEW Medium Deep" },
      { hex_value: "#D1997B", colour_name: "NEW Medium Caramel" },
      { hex_value: "#B17439", colour_name: "NEW Golden Honey" },
      { hex_value: "#BC6A21", colour_name: "NEW Deep Caramel" },
      { hex_value: "#AE631B", colour_name: "NEW Deeper Caramel" },
      { hex_value: "#F99673", colour_name: "Medium" },
    ],
  },
  {
    _id: "639aab3096d129b1f7d74160",
    id: 820,
    brand: "clinique",
    name: "Beyond Perfecting&trade; Super Concealer Camouflage + 24-Hour Wear",
    price: "19.5",
    price_sign: "$",
    currency: "USD",
    image_link:
      "https://www.clinique.com/media/export/cms/products/181x209/clq_K2HW01_181x209.png",
    product_link:
      "https://www.clinique.com/product/1596/50424/makeup/concealers/beyond-perfecting-super-concealer-camouflage-24-hour-wear",
    website_link: "https://www.clinique.com",
    description:
      "Cover up without touching up for 24 life-proof hours. Instantly and easily blends into skin to flawlessly conceal imperfections. Transfer-resistant formula stays put—even through sweat and humidity. Provides immediate hydration to keep eye-area skin feeling comfortable, looking fresh and natural. 18 shades in total—including a must-have apricot-colored corrector shade to help tackle dark circles and discolorations.",
    rating: null,
    category: "concealer",
    product_type: "foundation",
    tag_list: [],
    created_at: "2017-12-23T23:42:57.925Z",
    updated_at: "2017-12-23T23:43:02.839Z",
    product_api_url: "http://makeup-api.herokuapp.com/api/v1/products/820.json",
    api_featured_image:
      "//s3.amazonaws.com/donovanbailey/products/api_featured_images/000/000/820/original/data?1514072582",
    product_colors: [
      { hex_value: "#E8B99A", colour_name: "Very Fair 02" },
      { hex_value: "#E9B894", colour_name: "Very Fair 04" },
      { hex_value: "#E4AD85", colour_name: "Very Fair 05" },
      { hex_value: "#E3AB7F", colour_name: "Very Fair 06" },
      { hex_value: "#DFAC8B", colour_name: "Very Fair 07" },
      { hex_value: "#E4AD87", colour_name: "Very Fair 08" },
      { hex_value: "#DCA68A", colour_name: "Moderately Fair 10" },
      { hex_value: "#CF916B", colour_name: "Moderately Fair 12" },
      { hex_value: "#D59972", colour_name: "Moderately Fair 14" },
      { hex_value: "#D3936C", colour_name: "Medium 16" },
      { hex_value: "#CD9571", colour_name: "Medium 18" },
      { hex_value: "#C58F64", colour_name: "Medium 20" },
      { hex_value: "#BF8562", colour_name: "Medium 22" },
      { hex_value: "#CB8964", colour_name: "Medium 15" },
      { hex_value: "#BA7F53", colour_name: "Deep 24" },
      { hex_value: "#E5855E", colour_name: "Apricot Corrector" },
      { hex_value: "#996454", colour_name: "Deep 26" },
      { hex_value: "#8b594c", colour_name: "Deep 28" },
    ],
  },
];
